- name: Copy chart overrides values
  template:
    src: "demo-builder-values.yaml.j2"
    dest: "/root/govstack/usct_backend/sandbox-demo-builder/use-cases/usct-full/demo-builder-values.yaml"
    mode: '0755'

- name: Copy run migration scripts
  template:
    src: "run_migrations.sh.j2"
    dest: "/root/run_migrations.sh"
    mode: '0755'

- name: Install USCT
  shell: |
    cd /root/govstack/usct_backend/sandbox-demo-builder/use-cases
    helm dependency update ./usct-full/
    helm upgrade --install usct ./usct-full/ --create-namespace --namespace {{usct_namespace}} --values /root/govstack/usct_backend/sandbox-demo-builder/use-cases/usct-full/demo-builder-values.yaml

- name: Wait for deployments
  shell: bash /root/check_deployment.sh {{usct_namespace}}


- name: Enable openimis backend
  set_fact:
    open_imis_backend_enabled: true

- name: Copy chart overrides values
  template:
    src: "demo-builder-values.yaml.j2"
    dest: "/root/govstack/usct_backend/sandbox-demo-builder/use-cases/usct-full/demo-builder-values.yaml"
    mode: '0755'


- name: Install USCT with openimis backend
  shell: |
    cd /root/govstack/usct_backend/sandbox-demo-builder/use-cases
    helm dependency update ./usct-full/
    helm upgrade --install usct ./usct-full/ --create-namespace --namespace {{usct_namespace}} --values /root/govstack/usct_backend/sandbox-demo-builder/use-cases/usct-full/demo-builder-values.yaml

- name: Wait for deployments
  shell: bash /root/check_deployment.sh {{usct_namespace}}

- name: Run open imis migrations
  shell: bash /root/run_migrations.sh

- name: Wait for deployments in usct namespace
  shell: bash /root/check_deployment.sh sandbox-im