- name: Define MySQL deployment
  template:
    src: "mysql-deployment.yaml.j2"
    dest: "/root/joget/mysql-deployment.yaml"
    mode: '0755'

- name: Define Joget deployment
  template:
    src: "joget-dx8-tomcat9-deployment.yaml.j2"
    dest: "/root/joget/joget-dx8-tomcat9-deployment.yaml"
    mode: '0755'

- name: Define change admin password script
  template:
    src: "change_joget_admin_password.sh.j2"
    dest: "/root/joget/change_joget_admin_password.sh"
    mode: '0755'

- name: Generate hashed admin password
  ansible.builtin.shell: "echo -n '{{ joget_password_plain }}' | md5sum | awk '{print $1}'"
  register: joget_password

- name: Set joget_admin_password with hashed value
  ansible.builtin.set_fact:
    joget_admin_password: "{{ joget_password.stdout }}"

- name: "Define MySQL script"
  template:
    src: "jwdb-mysql.sql.j2"
    dest: "/root/joget/jwdb-mysql.sql"
    mode: "0755"

- name: Create configmap for jwdb using MySQL script
  shell: |
    echo 'hashed password: {{ joget_admin_password }}'
    kubectl -n {{joget_namespace}} create configmap jwdb-sql-config --from-file=/root/joget/jwdb-mysql.sql

# "kubectl -n $JOGETNAMESPACE create configmap jwdb-sql-config --from-file=/home/ubuntu/workspace/jwdb-mysql.sql"


# - name: Install joget
#   shell: |
#     cd /root/govstack/joget_backend/sandbox-demo-builder/use-cases
#     helm dependency update ./joget-full/
#     helm upgrade --install joget ./joget-full/ --create-namespace --namespace {{joget_namespace}} --values /root/govstack/joget_backend/sandbox-demo-builder/use-cases/joget-full/demo-builder-values.yaml

# - name: Wait for deployments
#   shell: bash /root/check_deployment.sh {{joget_namespace}}


# - name: Enable openimis backend
#   set_fact:
#     open_imis_backend_enabled: true

# - name: Copy chart overrides values
#   template:
#     src: "demo-builder-values.yaml.j2"
#     dest: "/root/govstack/joget_backend/sandbox-demo-builder/use-cases/joget-full/demo-builder-values.yaml"
#     mode: '0755'

# - name: Install joget with openimis backend
#   shell: |
#     cd /root/govstack/joget_backend/sandbox-demo-builder/use-cases
#     helm dependency update ./joget-full/
#     helm upgrade --install joget ./joget-full/ --create-namespace --namespace {{joget_namespace}} --values /root/govstack/joget_backend/sandbox-demo-builder/use-cases/joget-full/demo-builder-values.yaml

# - name: Wait for deployments
#   shell: bash /root/check_deployment.sh {{joget_namespace}}
