# The defaults folder contains a main.yaml file that defines default variables for the role.
# Variables in defaults/main.yaml have the lowest precedence, meaning they can be easily overridden by other variables in your playbooks, inventory, or other variable files.
joget_namespace: joget-app
joget_prefix: joget

pvc_access_mode: "ReadWriteOnce"
pvc_size: 20
mysql_version: "8.0"

joget_image_name: jogetworkflow/joget-dx8-tomcat9
joget_image_tag: 8.1.4
joget_endpoint: "joget.test.example"
